[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_eksi = "5pLRRFDgRaQUHoHUuKNjvj5worF9ZuroqKcyVvMjyNgL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/sulukarpuz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
